### ISSUE TITLE
no such file

### ISSUE THREAD

**Issue by krisele** [ivanus0/iProg-script-disasm#11]
Hello, after launching I keep getting an error that there is no file, the file with the .ipr extension is in the same folder as the source code, what's wrong?

`S C:\Users\KZ> & C:/Users/KZ/AppData/Local/Programs/Python/Python312/python.exe c:/Users/KZ/Downloads/cars/iProg-script-disasm-master/iProgDecompiler.py testfile 

Processing: testfile
No such file
PS C:\Users\KZ> `

**Comment by ivanus0** [comment]
The file name must be specified with the extension:
`iProgDecompiler.py testfile.ipr`

**Comment by krisele** [comment]
I gave it and the same thing, I probably had the wrong permissions, I moved the project to another place and it's ok. Thank you for the quick reply.

**Comment by krisele** [comment]
You can contact us in other ways than by telegram, e.g. email, do you have a question?

**Comment by ivanus0** [comment]
Leave your contact
