### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters

### ISSUE THREAD

**Issue by y509108** [ivanus0/iProg-script-disasm#3]
Hi,
i`m trying to decompile one ipr file but getting below error:

$ python iProgDecompiler.py MB96F615A.ipr
Processing: MB96F615A.ipr
## device bytecode is DES encoded (iprog sn=1)
EOF OK
Traceback (most recent call last):
  File "C:\projects\iProg-script-disasm\iProgDecompiler.py", line 42, in <module>
    decompile(filename)
  File "C:\projects\iProg-script-disasm\iProgDecompiler.py", line 34, in decompile
    decompile_ipr(source_filename)
  File "C:\projects\iProg-script-disasm\iProgDecompiler.py", line 11, in decompile_ipr
    f.write('\n'.join(ipr.get_lst()))
  File "C:\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 243-250: character maps to <undefined>

Attaching the ipr file.

What can be the issue?
[MB96F615A.zip](https://github.com/ivanus0/iProg-script-disasm/files/13888804/MB96F615A.zip)

Regards,
Stefan

**Comment by ivanus0** [comment]
Please check with the latest commit

**Comment by y509108** [comment]
Thanks, now decompile is working properly.

**Comment by ivanus0** [comment]
Decompiled and added to examples
