### ISSUE TITLE
uPD70F3628 (256 KByte + 32 KByte) decompile

### ISSUE THREAD

**Issue by Olega1987** [ivanus0/iProg-script-disasm#7]
Hello. Could you please add this script decompiled to the folder?
[uPD70F3628 (256 KByte + 32 KByte).zip](https://github.com/ivanus0/iProg-script-disasm/files/14811203/uPD70F3628.256.KByte.%2B.32.KByte.zip)

**Comment by ivanus0** [comment]
Yep 3c9ed1b

**Comment by Olega1987** [comment]
Thank you.
