### ISSUE TITLE
Iprog

### ISSUE THREAD

**Issue by rahhal81** [ivanus0/iProg-script-disasm#8]
Hi , how can i convert the script from (ipr) to (blr) as the example u post , decompiler its blr 
But when i try the script i get (lst) and ipr
Please can u help to understand 
Thanks for ur support.

**Comment by ivanus0** [comment]
There is currently no way to get .blr in automatic mode, a detailed answer is here https://github.com/ivanus0/iProg-script-disasm/commit/49043f2bc024bac67ae4cdc26e35eaed002638f0#commitcomment-137856953
