### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by rahhal81** [ivanus0/iProg-script-disasm#9]
Hi,
can u help me please to make (blr) code for this aacript 
and please there is script or way to compiled the script with serial number again . 
thanks for ur support ..
[evap off.zip](https://github.com/ivanus0/iProg-script-disasm/files/15367504/evap.off.zip)

**Comment by ivanus0** [comment]
Something like this [DENSO_TOYOTA_PETROL_EVAP_OFF.zip](https://github.com/ivanus0/iProg-script-disasm/files/15369042/DENSO_TOYOTA_PETROL_EVAP_OFF.zip)

What reason is there to compile a script with a serial number?

**Comment by rahhal81** [comment]
thanks for your help and support ,
I have question  ;
I notice in script (writesn19.blr) to change serial number the script use this value below :
0xEEA1E690	// 1
0x4A354204	// 19
0xB4CABCFB	// 45
my question how generate value from serial number ?  
for example if i want make script (writesn5555.blr)to change devise serial number to (5555) what the value 0x should be, and how calculate .
thanks

**Comment by rahhal81** [comment]
> What reason is there to compile a script with a serial number?

to return the (blr) code back to (ipr) even without complied with serial number , just after i finish my blr cade i want return it to ipr

**Comment by ivanus0** [comment]
> how generate value from serial number ?

You can view the algorithm in [this](https://github.com/ivanus0/iProg-script-disasm/blob/master/examples/decompiled/writesn.blr) file
Or just uncomment a few lines and see all the values in the log

**Comment by rahhal81** [comment]
Thank for support, 
Best regard.

**Comment by rahhal81** [comment]
Very helpful 
Thanks

**Comment by rahhal81** [comment]
How can I contact you directly? I have some question and project , 
This is my email: navipro8185@gmail.com

**Comment by ivanus0** [comment]
https://t.me/sllogbot?start=contact
